config/routes.rb
Rails.application.routes.draw do
 
  resources :sheets
  resources :activities
  resources :clients do
    collection {post :import}
  end

  root to: 'pages#home'

  
  get '/exporttwinfield'=> 'pages#exporttwinfield'

  get '/about'=> 'pages#about'

end

app/models/activity.rb
class Activity < ActiveRecord::Base
	has_many :sheets
end

app/models/client.rb
class Client < ActiveRecord::Base

	has_many :sheets

	def self.import(file)
		::CSV.foreach(file.path, headers: true) do |row|
			Client.create! row.to_hash
		end
	end
end

app/models/sheet.rb
class Sheet < ActiveRecord::Base
	belongs_to :client 
	belongs_to :activity
	
	validates :client_id, presence: true
	validates :activity_id, presence: true

	def client_name
		client.try(:name)
	end

	def client_name=(name)
		self.client = Client.find_by_name(name) if name.present?
		
	end

	def activity_name
		activity.try(:name)
	end

	def activity_name=(name)
		self.activity = Activity.find_by_name(name) if name.present?
		
	end

end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: [:show, :edit, :update, :destroy]

  # GET /activities
  # GET /activities.json
  def index
    @activities = Activity.all
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
  end

  # GET /activities/new
  def new
    @activity = Activity.new
  end

  # GET /activities/1/edit
  def edit
  end

  # POST /activities
  # POST /activities.json
  def create
    @activity = Activity.new(activity_params)

    respond_to do |format|
      if @activity.save
        format.html { redirect_to @activity, notice: 'Activity was successfully created.' }
        format.json { render :show, status: :created, location: @activity }
      else
        format.html { render :new }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1
  # PATCH/PUT /activities/1.json
  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to @activity, notice: 'Activity was successfully updated.' }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity.destroy
    respond_to do |format|
      format.html { redirect_to activities_url, notice: 'Activity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activity_params
      params.require(:activity).permit(:name, :short_code)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  def import
    Client.import(params[:file])
    redirect_to clients_path, notice: "Clients imported"
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:code, :name )
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

	def exporttwinfield
		@sheets = Sheet.all.order('date ASC')
	end

end

app/controllers/sheets_controller.rb
class SheetsController < ApplicationController
  before_action :set_sheet, only: [:show, :edit, :update, :destroy]

  # GET /sheets
  # GET /sheets.json
  def index
    @sheets = Sheet.all.order('date ASC')
     respond_to do |format|
     format.html { render :index }
     format.xml {
     render :xml => @sheets.to_xml
    }
    end
  end

  # GET /sheets/1
  # GET /sheets/1.json
  def show
  end

  # GET /sheets/new
  def new
    @sheet = Sheet.new
  end

  # GET /sheets/1/edit
  def edit
  end

  # POST /sheets
  # POST /sheets.json
  def create
    @sheet = Sheet.new(sheet_params)
    
      if @sheet.save

        redirect_to '/sheets/new', notice: 'Your Sheet has been saved successfully' 
       # format.html { render :new, notice: 'Sheet was successfully created.' }
        
      else
         render :new 
       
      end
  end
 

  # PATCH/PUT /sheets/1
  # PATCH/PUT /sheets/1.json
  def update
    respond_to do |format|
      if @sheet.update(sheet_params)
        format.html { redirect_to @sheet, notice: 'Sheet was successfully updated.' }
        format.json { render :show, status: :ok, location: @sheet }
      else
        format.html { render :edit }
        format.json { render json: @sheet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sheets/1
  # DELETE /sheets/1.json
  def destroy
    @sheet.destroy
    respond_to do |format|
      format.html { redirect_to sheets_url, notice: 'Sheet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sheet
      @sheet = Sheet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sheet_params
      params.require(:sheet).permit(:date, :client_id, :activity_id, :omschrijving, :uur, :minuten, :antal, :opmerking_intern, :client_name, :activity_name, :uren_type)
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sheets_helper.rb
module SheetsHelper
end

app/views/activities/_form.html.erb
<%= form_for(@activity) do |f| %>
  <% if @activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
      <% @activity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  
  <div class="field">
    <%= f.label :short_code %><br>
    <%= f.text_field :short_code %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/activities/edit.html.erb
<h1>Editing Activity</h1>

<%= render 'form' %>

<%= link_to 'Show', @activity %> |
<%= link_to 'Back', activities_path %>

app/views/activities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Activities</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Short code</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @activities.each do |activity| %>
      <tr>
        <td><%= activity.name %></td>
        <td><%= activity.short_code %></td>
        <td><%= link_to 'Show', activity %></td>
        <td><%= link_to 'Edit', edit_activity_path(activity) %></td>
        <td><%= link_to 'Destroy', activity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Activity', new_activity_path %>

app/views/activities/new.html.erb
<h1>New Activity</h1>

<%= render 'form' %>

<%= link_to 'Back', activities_path %>

app/views/activities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @activity.name %>
</p>

<p>
  <strong>Short code:</strong>
  <%= @activity.short_code %>
</p>

<%= link_to 'Edit', edit_activity_path(@activity) %> |
<%= link_to 'Back', activities_path %>

app/views/clients/_form.html.erb
<%= form_for(@client) do |f| %>
  <% if @client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% @client.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :code %><br>
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing Client</h1>

<%= render 'form' %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Clients Details</h1>

<table class=" table table-hover" >
  <thead>
    <tr>
      <th>Code</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.code %></td>
        <td><%= client.name %></td>
        <td><%= link_to 'Show', client %></td>
        <td><%= link_to 'Edit', edit_client_path(client) %></td>
        <td><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<%= link_to 'New Client', new_client_path %>
<br> Or
<p>
  <strong>Import Client:</strong>
  <%= form_tag import_clients_path, multipart: true do%>
    <%= file_field_tag :file%>
    <%= submit_tag "import"%>
  <% end %>
</p>

app/views/clients/new.html.erb
<h1>New Client</h1>

<%= render 'form' %>

<%= link_to 'Back', clients_path %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @client.code %>
</p>

<p>
  <strong>Name:</strong>
  <%= @client.name %>
</p>



<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Timesheet</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="container">

	<div>
					
			<div class="pull-right">
				
				<font color= #005478><%=link_to "Home", "/" , class: "btn btn-erik" %>
					
				<font color= #005478> <%=link_to "About", "/about" , class: "btn btn-erik"%> </font>
				<font color= #005478> <%=link_to "Clients controller", "/clients" , class: "btn btn-erik"%> </font>
				<font color= #005478> <%=link_to "Activities controller", "/activities" , class: "btn btn-erik"%> </font>
				<font color= #005478> <%=link_to "Sheet controller", "/sheets" , class: "btn btn-erik"%> </font>
				
				
			</div>

				
	</div>
	<br>
	<br>
<div>

<%= yield %>

</div>
</body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/exporttwinfield.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Sheets</h1> 


<table class="table table-hover">
  <thead>
    <tr>
      <th>Date</th>
      <th>Client</th>
      <th>Activity</th>
      <th>Omschrijving</th>
      <th>Uur</th>
      <th>Minuten</th>
      <th>Antal</th>
      <th>Opmerking intern</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sheets.each do |sheet| %>
      <tr>
        <td><%= sheet.date.strftime("%d/%m/%Y") %></td>
        <td><%= Client.find(sheet.client_id).name %></td>
        <td><%= Activity.find(sheet.activity_id).name %></td>
        <td><%= sheet.omschrijving %></td>
        <td><%= sheet.uur %></td>
        <td><%= sheet.minuten %></td>
        <td><%= sheet.antal %></td>
        <td><%= sheet.opmerking_intern %></td>
        <td><%= link_to 'Show', sheet %></td>
        <td><%= link_to 'Edit', edit_sheet_path(sheet) %></td>
        <td><%= link_to 'Destroy', sheet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sheet', new_sheet_path %>

app/views/pages/home.html.erb
<div >
	<h1>Pages#home</h1>
	<p>Find me in app/views/pages/home.html.erb</p>
</div>

app/views/sheets/_form.html.erb
<%= form_for(@sheet) do |f| %>
  <% if @sheet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sheet.errors.count, "error") %> prohibited this sheet from being saved:</h2>

      <ul>
      <% @sheet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="form-group">
    <%= f.hidden_field :uren_type, :value => "DIRECT" %>

    <%= f.label :date %> &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp  &nbsp &nbsp 
    <%= f.label :client_name %> &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp 
    <%= f.label :activity_name %> &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp
     <%= f.label :omschrijving %><br>
    <br>

    <%= f.text_field :date, class: "sheet_date"%>
      &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp 
    
    <%= f.text_field :client_name, data: {autocomplete_source: Client.order(:name).map(&:name)} %>
      &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp 
    
    <%= f.text_field :activity_name, data: {autocomplete_source: Activity.order(:name).map(&:name)} %>
    &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp  

     <%= f.text_area :omschrijving, :maxlength => 80 , style: "width: 300px; height: 25px"  %>
<hr>
  </div>


  <div class="field">
   
   <%= f.label :uur %> &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp  &nbsp &nbsp 
    <%= f.label :minuten %>&nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp 
  
     <%= f.label :antal %>&nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp  
    <%= f.label :opmerking_intern %><br>

    <%= f.text_field :uur, class: "hours" %>&nbsp &nbsp &nbsp &nbsp &nbsp &nbsp 
  
    <%= f.text_field :minuten, class: "minute" %>&nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp 
 
   
    <%= f.text_field :antal %>&nbsp &nbsp &nbsp &nbsp &nbsp &nbsp 
 
 
  
    <%= f.text_area :opmerking_intern , style: "width: 300px; height: 25px" %>

  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sheets/edit.html.erb
<h1>Editing Sheet</h1>

<%= render 'form' %>

<%= link_to 'Show', @sheet %> |
<%= link_to 'Back', sheets_path %>

app/views/sheets/index.html.erb
<h2>This is the final output for twinfield </h2>
 <h2> <a href="/sheets.xml">link_to click here for xml</a></h2>
<table class="table table-hover" "width=70%">
  <thead>
    <tr>
      <th>Uren Type</th>
      <th>Garibuker</th>
      <th>Datum</th>
      <th>Project</th>
      <th>Activity</th>
      <th width="170px" >Duration in Minuten</th>
      <th>Omschrijving</th>
      
    </tr>
  </thead>

  <tbody>
    <% @sheets.each do |sheet| %>
      <tr>
        <td><%= sheet.uren_type %></td>
        <td><%= "0" %></td>
        <td><%= sheet.date.strftime("%d/%m/%Y") %></td>
        <td><%= Client.find(sheet.client_id).code %></td>
        <td><%= Activity.find(sheet.activity_id).short_code %></td>
        <td align="right"><%= sheet.minuten %></td>
        <td><%= sheet.omschrijving %></td>
              
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/sheets/new.html.erb
<p id="notice"><%= notice %></p>

<h1>New Sheet</h1>


<%= render 'form' %>

<%= link_to 'Back', sheets_path %>

app/views/sheets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @sheet.date %>
</p>

<p>
  <strong>Client:</strong>
  
  <%= @sheet.client.name %>

</p>


<p>
  <strong>Activity:</strong>
  <%= Activity.find(@sheet.activity_id).name %>

  &nbsp
  
</p>

<p>
  <strong>Omschrijving:</strong>
  <%= @sheet.omschrijving %>
</p>

<p>
  <strong>Uur:</strong>
  <%= @sheet.uur %>
</p>

<p>
  <strong>Minuten:</strong>
  <%= @sheet.minuten %>
</p>

<p>
  <strong>Antal:</strong>
  <%= @sheet.antal %>
</p>

<p>
  <strong>Opmerking intern:</strong>
  <%= @sheet.opmerking_intern %>
</p>

<%= link_to 'Edit', edit_sheet_path(@sheet) %> |
<%= link_to 'Back', sheets_path %>